project_name: iptv-proxy

builds:
  - binary: iptv-proxy
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor
      - -a
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  -
   format_overrides:
     - goos: windows
       format: zip

release:
  github:
    owner: gibby
    name: iptv-proxy
  draft: false
